### **Import Library**


In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [48]:
from google.colab import files
uploaded = files.upload()

Saving House Price India.csv to House Price India (1).csv


In [49]:
dataset_train=pd.read_csv("/content/House Price India.csv")

In [50]:
dataset_train.head()

id   Date  number of bedrooms  number of bathrooms  living area  \
0  6762810145  42491                   5                 2.50         3650   
1  6762810635  42491                   4                 2.50         2920   
2  6762810998  42491                   5                 2.75         2910   
3  6762812605  42491                   4                 2.50         3310   
4  6762812919  42491                   3                 2.00         2710   

   lot area  number of floors  waterfront present  number of views  \
0      9050               2.0                   0                4   
1      4000               1.5                   0                0   
2      9480               1.5                   0                0   
3     42998               2.0                   0                0   
4      4500               1.5                   0                0   

   condition of the house  ...  Built Year  Renovation Year  Postal Code  \
0                       5  ...        1921                0       122003   
1                       5  ...        1909                0       122004   
2                       3  ...        1939                0       122004   
3                       3  ...        2001                0       122005   
4                       4  ...        1929                0       122006   

   Lattitude  Longitude  living_area_renov  lot_area_renov  \
0    52.8645   -114.557               2880            5400   
1    52.8878   -114.470               2470            4000   
2    52.8852   -114.468               2940            6600   
3    52.9532   -114.321               3350           42847   
4    52.9047   -114.485               2060            4500   

   Number of schools nearby  Distance from the airport    Price  
0                         2                         58  2380000  
1                         2                         51  1400000  
2                         1                         53  1200000  
3                         3                         76   838000  
4                         1                         51   805000  

[5 rows x 23 columns]

## **1. Preprocess the Dataset**

In [51]:
X = dataset_train.iloc[:, 1:2].values 
y = dataset_train.iloc[:, -1].values


In [52]:
X


array([[42491],
       [42491],
       [42491],
       ...,
       [42734],
       [42734],
       [42734]])

In [53]:
y

array([2380000, 1400000, 1200000, ...,  209000,  205000,  146000])

In [54]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [55]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train

array([[-1.16155586],
       [-1.08747669],
       [ 0.67560763],
       ...,
       [ 0.55708096],
       [ 0.79413431],
       [-1.01339751]])

In [56]:
X_test

array([[-0.4503958 ],
       [ 1.12008267],
       [-0.80597583],
       ...,
       [-1.29489837],
       [ 0.08297425],
       [-1.28008254]])

## **2.Build the ANN Model**





# Initializing the ANN

In [57]:
ann = tf.keras.models.Sequential()

# Add the input layer and first hidden layer

In [58]:
ann.add(tf.keras.layers.Dense(units=12, activation='relu', input_shape=X_train[0].shape))

# Add the second hidden layer

In [59]:
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))

# Add the output layer


In [60]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# **3. Test the Model**

In [61]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
pd.DataFrame(list(zip(y_test, y_pred)), columns=['Actual', 'Predicted'])

92/92 [==============================] - 0s 1ms/step


Actual Predicted
0      269000    [True]
1     1160000   [False]
2      410000    [True]
3      540000    [True]
4      657500    [True]
...       ...       ...
2919  1250000   [False]
2920   525000    [True]
2921   544500    [True]
2922   260000   [False]
2923   405000    [True]

[2924 rows x 2 columns]

In [62]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]
0.0
